### ISSUE TITLE
What version of puppet?

### ISSUE THREAD

**Issue by kenmiller316** [ULHPC/puppet-multipath#1]
Hello,

I am trying to use 0.1.4 with puppet 4.10 and a simple 'include multipath' yields what looks to be a variable scope error (e.g. undefined $::multipath_ensure).

What version(s) of puppet are supported with this module?

Thanks,

== k+ ==

**Comment by hcartiaux** [comment]
I've released a new version tested with puppet 4.10.10.

Note that this is initially a port of a puppet 2.6 module, used on around 10 servers with only 4 different configuration. This new module is not yet used in production. Use at your own risk ;)
