### ISSUE TITLE
basic usage is broken?

### ISSUE THREAD

**Issue by rgevaert** [ULHPC/puppet-multipath#3]
Hi,
I'm trying to use the module with:
```
  include ::multipath
  multipath::device { 'MD38xxi':
    ensure  => 'present',
    vendor  => 'DELL',  # As reported by
    product => 'MD38xxi', # /proc/scsi/scsi
  }
```
That creates an /etc/multipath.conf.new file. 
Overridding configfile works, but then you get:

Warning: /Stage[main]/Iscsi_client/Multipath::Device[MD38xxi]/Concat::Fragment[/etc/multipath.conf.new_device_DELL]/Concat_fragment[/etc/multipath.conf.new_device_DELL]: Target Concat_file[/etc/multipath.conf.new] not found in the catalog

Because of

```
    concat::fragment { "${multipath::params::configfile}_multipath_${wwid}":
        target  => $multipath::params::configfile,
        order   => '60',
        content => $real_content,
        source  => $real_source,
        notify  => Service['multipath'],
    }
```
in manifests/path.pp, the target should be $multipath::configfile,

How are you using this module?

**Comment by hcartiaux** [comment]
This is a normal behavior.
It creates the file `multipath.conf.new`, we double check manually that the configuration file is correct before using it, and then we copy it to `/etc/multipath.conf`.
