### ISSUE TITLE
PDK compatibility and supported OS/Puppet versions

### ISSUE THREAD

**Issue by tuxmea** [ULHPC/puppet-multipath#4]
Please migrate to PDK so we have proper list of supported OS and Puppet versions.
We (example42) will mention your mode as replacement for our multipath module.

**Comment by hcartiaux** [comment]
Unfortunately, we do not use this module in production anymore and I have no way to test it at the moment...

Feel free to fork or contact another fork owner, such as [thunderpants73](https://github.com/thunderpants73) /
[puppet-multipath](https://github.com/thunderpants73/puppet-multipath).

Thank you
